import type { Offer, Referral, AppNotification, AuditEntry, SystemService } from "./types";

// All data in this file is illustrative sample data for features that do not
// yet have a live backend (offers, referrals, notifications, audit log).
// Structured behind services.ts so real endpoints can replace it later.

const now = Date.now();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();
const daysAhead = (d: number) => new Date(now + d * 86_400_000).toISOString();

export const SAMPLE_OFFERS: Offer[] = [
  {
    id: "of_eid",
    name: "Eid Celebration Offer",
    code: "EID25",
    description: "Season savings on all Luxor PDF paid plans during Eid week.",
    occasion: "Eid",
    discountType: "percent",
    discountValue: 25,
    products: ["PDF Secure", "PDF Reader"],
    plans: ["monthly", "yearly"],
    eligibleUsers: "everyone",
    countries: ["All"],
    validFrom: daysAhead(20),
    validTo: daysAhead(27),
    usageLimit: 500,
    perUserLimit: 1,
    timesUsed: 0,
    minPurchase: null,
    maxDiscount: null,
    autoApply: false,
    isPublic: true,
    status: "Scheduled",
  },
  {
    id: "of_newyear",
    name: "New Year Sale",
    code: "NY2026",
    description: "Start the year organized — discount on yearly plans.",
    occasion: "New Year",
    discountType: "percent",
    discountValue: 30,
    products: ["PDF Secure", "PDF Reader", "eSign"],
    plans: ["yearly", "lifetime"],
    eligibleUsers: "everyone",
    countries: ["All"],
    validFrom: daysAgo(196),
    validTo: daysAgo(182),
    usageLimit: 1000,
    perUserLimit: 1,
    timesUsed: 214,
    minPurchase: null,
    maxDiscount: 50,
    autoApply: true,
    isPublic: true,
    status: "Expired",
  },
  {
    id: "of_summer",
    name: "Summer Campaign",
    code: "SUMMER15",
    description: "Mid-year boost for new subscribers.",
    occasion: "Summer",
    discountType: "percent",
    discountValue: 15,
    products: ["PDF Secure"],
    plans: ["monthly", "quarterly"],
    eligibleUsers: "new",
    countries: ["United States", "United Kingdom", "Canada"],
    validFrom: daysAgo(14),
    validTo: daysAhead(31),
    usageLimit: null,
    perUserLimit: 1,
    timesUsed: 37,
    minPurchase: null,
    maxDiscount: null,
    autoApply: false,
    isPublic: true,
    status: "Active",
  },
  {
    id: "of_launch",
    name: "Product Launch Offer",
    code: "LAUNCH10",
    description: "Celebrate the eSign launch with a fixed discount.",
    occasion: "Product Launch",
    discountType: "fixed",
    discountValue: 10,
    products: ["eSign"],
    plans: ["monthly", "yearly"],
    eligibleUsers: "everyone",
    countries: ["All"],
    validFrom: daysAhead(7),
    validTo: daysAhead(37),
    usageLimit: 300,
    perUserLimit: 1,
    timesUsed: 0,
    minPurchase: 20,
    maxDiscount: null,
    autoApply: false,
    isPublic: false,
    status: "Draft",
  },
  {
    id: "of_bf",
    name: "Black Friday Offer",
    code: "BLACK40",
    description: "Biggest discount of the year across every plan.",
    occasion: "Black Friday",
    discountType: "percent",
    discountValue: 40,
    products: ["PDF Secure", "PDF Reader", "eSign"],
    plans: ["monthly", "quarterly", "yearly", "lifetime"],
    eligibleUsers: "everyone",
    countries: ["All"],
    validFrom: daysAhead(130),
    validTo: daysAhead(134),
    usageLimit: 2000,
    perUserLimit: 1,
    timesUsed: 0,
    minPurchase: null,
    maxDiscount: 120,
    autoApply: true,
    isPublic: true,
    status: "Scheduled",
  },
  {
    id: "of_referral",
    name: "Referral Bonus",
    code: "FRIEND10",
    description: "Automatic 10% off for customers arriving via referral links.",
    occasion: "Referral Program",
    discountType: "percent",
    discountValue: 10,
    products: ["PDF Secure", "PDF Reader", "eSign"],
    plans: ["monthly", "quarterly", "yearly"],
    eligibleUsers: "new",
    countries: ["All"],
    validFrom: daysAgo(90),
    validTo: daysAhead(275),
    usageLimit: null,
    perUserLimit: 1,
    timesUsed: 12,
    minPurchase: null,
    maxDiscount: null,
    autoApply: true,
    isPublic: false,
    status: "Active",
  },
  {
    id: "of_loyalty",
    name: "Customer Loyalty Offer",
    code: "LOYAL2M",
    description: "Two bonus months of validity for long-time subscribers.",
    occasion: "Loyalty",
    discountType: "extension",
    discountValue: 60,
    products: ["PDF Secure"],
    plans: ["yearly"],
    eligibleUsers: "existing",
    countries: ["All"],
    validFrom: daysAgo(5),
    validTo: daysAhead(25),
    usageLimit: 200,
    perUserLimit: 1,
    timesUsed: 8,
    minPurchase: null,
    maxDiscount: null,
    autoApply: false,
    isPublic: false,
    status: "Paused",
  },
];

export const SAMPLE_REFERRALS: Referral[] = [
  {
    id: "rf_1",
    referrer: "jane@sample.luxorpdf.com",
    code: "JANE10",
    link: "https://luxorpdf.com/r/JANE10",
    clicks: 148,
    signups: 22,
    paidConversions: 6,
    revenue: 342,
    discountGiven: 38,
    rewardGranted: true,
    status: "Reward Granted",
  },
  {
    id: "rf_2",
    referrer: "arjun@sample.luxorpdf.com",
    code: "ARJUN10",
    link: "https://luxorpdf.com/r/ARJUN10",
    clicks: 61,
    signups: 9,
    paidConversions: 2,
    revenue: 118,
    discountGiven: 13,
    rewardGranted: false,
    status: "Successful",
  },
  {
    id: "rf_3",
    referrer: "mia@sample.luxorpdf.com",
    code: "MIA10",
    link: "https://luxorpdf.com/r/MIA10",
    clicks: 34,
    signups: 4,
    paidConversions: 0,
    revenue: 0,
    discountGiven: 0,
    rewardGranted: false,
    status: "Registered",
  },
  {
    id: "rf_4",
    referrer: "omar@sample.luxorpdf.com",
    code: "OMAR10",
    link: "https://luxorpdf.com/r/OMAR10",
    clicks: 12,
    signups: 1,
    paidConversions: 1,
    revenue: 49,
    discountGiven: 5,
    rewardGranted: false,
    status: "Payment Pending",
  },
  {
    id: "rf_5",
    referrer: "li@sample.luxorpdf.com",
    code: "LI10",
    link: "https://luxorpdf.com/r/LI10",
    clicks: 210,
    signups: 40,
    paidConversions: 0,
    revenue: 0,
    discountGiven: 0,
    rewardGranted: false,
    status: "Fraud Review",
  },
];

export const SAMPLE_NOTIFICATIONS: AppNotification[] = [
  {
    id: "nt_1",
    kind: "success",
    title: "New yearly subscription",
    detail: "A customer upgraded to the Yearly plan via Stripe.",
    time: daysAgo(0.1),
    read: false,
  },
  {
    id: "nt_2",
    kind: "warning",
    title: "Offer ending soon",
    detail: "Summer Campaign (SUMMER15) ends in 31 days.",
    time: daysAgo(0.5),
    read: false,
  },
  {
    id: "nt_3",
    kind: "info",
    title: "Referral reward issued",
    detail: "JANE10 earned +2 months of validity.",
    time: daysAgo(1.2),
    read: false,
  },
  {
    id: "nt_4",
    kind: "error",
    title: "Failed payment",
    detail: "A Razorpay payment link attempt did not complete.",
    time: daysAgo(2.4),
    read: true,
  },
  {
    id: "nt_5",
    kind: "warning",
    title: "Activation limit reached",
    detail: "A license key hit its device activation limit.",
    time: daysAgo(3.1),
    read: true,
  },
];

export const SAMPLE_AUDIT_LOG: AuditEntry[] = [
  {
    id: "au_1",
    admin: "Admin",
    action: "License generated",
    target: "LUXOR-****-****-****",
    prev: "—",
    next: "active · yearly",
    time: daysAgo(0.3),
    ip: "127.0.0.1",
  },
  {
    id: "au_2",
    admin: "Admin",
    action: "Offer created",
    target: "SUMMER15",
    prev: "—",
    next: "Active",
    time: daysAgo(14),
    ip: "127.0.0.1",
  },
  {
    id: "au_3",
    admin: "Admin",
    action: "Quota override set",
    target: "customer",
    prev: "default",
    next: "custom limit",
    time: daysAgo(21),
    ip: "127.0.0.1",
  },
];

export const SYSTEM_SERVICES: SystemService[] = [
  { name: "API", status: "operational" },
  { name: "License Service", status: "operational" },
  { name: "Web App", status: "operational" },
  { name: "Database", status: "operational" },
  { name: "Storage", status: "operational" },
  { name: "Email Service", status: "operational" },
];

export const ACQUISITION_CHANNELS = [
  { name: "Organic Search", users: 412, pct: 38, conversion: 4.1, color: "#2563EB" },
  { name: "Direct", users: 287, pct: 26, conversion: 5.2, color: "#6D5DFB" },
  { name: "Referral", users: 141, pct: 13, conversion: 6.8, color: "#10B981" },
  { name: "Social Media", users: 118, pct: 11, conversion: 2.3, color: "#F59E0B" },
  { name: "Email", users: 76, pct: 7, conversion: 7.4, color: "#EF4444" },
  { name: "Paid Advertising", users: 54, pct: 5, conversion: 3.0, color: "#64748B" },
];

export const REGION_SAMPLE = [
  { country: "United States", users: 356, revenue: 4210, paid: 41, conversion: 4.2 },
  { country: "India", users: 298, revenue: 1890, paid: 33, conversion: 3.6 },
  { country: "United Kingdom", users: 122, revenue: 1140, paid: 14, conversion: 3.9 },
  { country: "Germany", users: 87, revenue: 820, paid: 9, conversion: 3.4 },
  { country: "Canada", users: 64, revenue: 610, paid: 7, conversion: 3.8 },
];

export const OPS_METRICS = [
  { label: "API Usage", value: "18.2K req/day", trend: [12, 14, 13, 16, 17, 18, 18] },
  { label: "App Downloads", value: "1,204", trend: [30, 34, 31, 38, 41, 44, 47] },
  { label: "Server Uptime", value: "99.98%", trend: [99, 99, 100, 100, 99, 100, 100] },
  { label: "Support Tickets", value: "7 open", trend: [11, 9, 12, 8, 9, 7, 7] },
  { label: "Failed Payments", value: "2 this week", trend: [4, 3, 5, 2, 3, 1, 2] },
  { label: "Email Delivery", value: "99.4%", trend: [98, 99, 99, 99, 100, 99, 99] },
  { label: "Activation Errors", value: "1 today", trend: [3, 2, 2, 1, 2, 1, 1] },
  { label: "Failed Logins", value: "12 (24h)", trend: [18, 14, 16, 11, 13, 10, 12] },
];

// ── Dev-preview sample data (design review without login; dev builds only) ──
import type { AdminStats, AdminCustomer, ProductKey, VisitorAnalytics } from "./types";

export const SAMPLE_STATS: AdminStats = {
  overview: {
    totalUsers: 128,
    paidUsers: 34,
    freeUsers: 94,
    totalRevenue: { USD: 2840, INR: 64500 },
    monthRevenue: { USD: 460, INR: 12800 },
    pageViews: 18432,
    totalPdfs: 512,
    activePdfs: 391,
    expiredPdfs: 121,
    totalStorageBytes: 1_874_512_384,
  },
  plans: { monthly: 14, quarterly: 6, yearly: 11, lifetime: 3 },
  monthlyData: [
    { month: "Feb", revenue: { USD: 180, INR: 4200 }, signups: 9 },
    { month: "Mar", revenue: { USD: 260, INR: 6900 }, signups: 14 },
    { month: "Apr", revenue: { USD: 310, INR: 8100 }, signups: 18 },
    { month: "May", revenue: { USD: 420, INR: 10400 }, signups: 22 },
    { month: "Jun", revenue: { USD: 510, INR: 11900 }, signups: 27 },
    { month: "Jul", revenue: { USD: 460, INR: 12800 }, signups: 21 },
  ],
  topPages: [
    { path: "/", views: 6120 },
    { path: "/pricing", views: 2840 },
    { path: "/pdf-expiry", views: 2410 },
    { path: "/luxor-pdf", views: 1980 },
    { path: "/features", views: 1240 },
    { path: "/download", views: 860 },
  ],
  dailyViews: Array.from({ length: 30 }, (_, i) => {
    const d = new Date(Date.now() - (29 - i) * 86_400_000);
    return {
      day: d.toISOString().slice(0, 10),
      views: 380 + Math.round(220 * Math.abs(Math.sin(i / 4))) + (i % 7 === 0 ? -120 : 0),
    };
  }),
  recentActivity: [
    { id: 1, type: "payment", user: "ava@sample.dev", message: "Yearly plan purchased (USD)", time: new Date(Date.now() - 32 * 60_000).toISOString() },
    { id: 2, type: "signup", user: "leo@sample.dev", message: "New account created", time: new Date(Date.now() - 2 * 3_600_000).toISOString() },
    { id: 3, type: "document", user: "mia@sample.dev", message: "Secured a PDF with 7-day expiry", time: new Date(Date.now() - 5 * 3_600_000).toISOString() },
    { id: 4, type: "payment", user: "raj@sample.dev", message: "Monthly plan renewed (INR)", time: new Date(Date.now() - 9 * 3_600_000).toISOString() },
    { id: 5, type: "signup", user: "zoe@sample.dev", message: "New account created", time: new Date(Date.now() - 22 * 3_600_000).toISOString() },
  ],
};

export const SAMPLE_CUSTOMERS: AdminCustomer[] = [
  {
    userId: "user_sample_ava", planName: "yearly", tier: "pro", isPaid: true,
    accountStatus: "active", lockReason: null,
    subscriptionStartDate: new Date(Date.now() - 40 * 86_400_000).toISOString(),
    subscriptionEndDate: new Date(Date.now() + 325 * 86_400_000).toISOString(),
    quotaOverrideSecure: null, monthlyUsed: 18, monthlyLimit: 100, monthlyRemaining: 82,
    passwordProtectUsed: 11, securePdfUsed: 7,
    resetDate: new Date(Date.now() + 12 * 86_400_000).toISOString(),
    createdAt: new Date(Date.now() - 90 * 86_400_000).toISOString(),
  },
  {
    userId: "user_sample_leo", planName: "monthly", tier: "pro", isPaid: true,
    accountStatus: "active", lockReason: null,
    subscriptionStartDate: new Date(Date.now() - 12 * 86_400_000).toISOString(),
    subscriptionEndDate: new Date(Date.now() + 18 * 86_400_000).toISOString(),
    quotaOverrideSecure: 250, monthlyUsed: 64, monthlyLimit: 250, monthlyRemaining: 186,
    passwordProtectUsed: 40, securePdfUsed: 24,
    resetDate: new Date(Date.now() + 18 * 86_400_000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 86_400_000).toISOString(),
  },
  {
    userId: "user_sample_mia", planName: null, tier: null, isPaid: false,
    accountStatus: "active", lockReason: null,
    subscriptionStartDate: null, subscriptionEndDate: null,
    quotaOverrideSecure: null, monthlyUsed: 3, monthlyLimit: 5, monthlyRemaining: 2,
    passwordProtectUsed: 2, securePdfUsed: 1,
    resetDate: new Date(Date.now() + 20 * 86_400_000).toISOString(),
    createdAt: new Date(Date.now() - 15 * 86_400_000).toISOString(),
  },
  {
    userId: "user_sample_raj", planName: "lifetime", tier: "pro", isPaid: true,
    accountStatus: "active", lockReason: null,
    subscriptionStartDate: new Date(Date.now() - 200 * 86_400_000).toISOString(),
    subscriptionEndDate: null,
    quotaOverrideSecure: null, monthlyUsed: 41, monthlyLimit: 100, monthlyRemaining: 59,
    passwordProtectUsed: 25, securePdfUsed: 16,
    resetDate: new Date(Date.now() + 5 * 86_400_000).toISOString(),
    createdAt: new Date(Date.now() - 220 * 86_400_000).toISOString(),
  },
];

export const SAMPLE_PRODUCT_KEYS: ProductKey[] = [
  {
    id: 9001, keyPrefix: "LUXOR-A1B2", planName: "yearly", durationDays: 365,
    maxActivations: 1, currentActivations: 1, status: "redeemed",
    expiresAt: null, notes: "Sample — giveaway batch",
    createdAt: new Date(Date.now() - 30 * 86_400_000).toISOString(), revokedAt: null,
  },
  {
    id: 9002, keyPrefix: "LUXOR-C3D4", planName: "monthly", durationDays: 30,
    maxActivations: 2, currentActivations: 0, status: "active",
    expiresAt: null, notes: "Sample — support goodwill",
    createdAt: new Date(Date.now() - 12 * 86_400_000).toISOString(), revokedAt: null,
  },
  {
    id: 9003, keyPrefix: "LUXOR-E5F6", planName: "lifetime", durationDays: 36_500,
    maxActivations: 1, currentActivations: 0, status: "revoked",
    expiresAt: null, notes: "Sample — issued in error",
    createdAt: new Date(Date.now() - 8 * 86_400_000).toISOString(),
    revokedAt: new Date(Date.now() - 2 * 86_400_000).toISOString(),
  },
];

export const SAMPLE_VISITOR_ANALYTICS: VisitorAnalytics = {
  days: Array.from({ length: 30 }, (_, i) => {
    const d = new Date(Date.now() - (29 - i) * 24 * 60 * 60 * 1000);
    const base = 40 + Math.round(30 * Math.sin(i / 4)) + (d.getDay() === 0 || d.getDay() === 6 ? -12 : 8);
    return { day: d.toISOString().slice(0, 10), visitors: Math.max(6, base + ((i * 7) % 11)) };
  }),
  locations: [
    { country: "IN", city: "Mumbai", visitors: 214 },
    { country: "IN", city: "Bengaluru", visitors: 187 },
    { country: "US", city: "New York", visitors: 132 },
    { country: "IN", city: "Delhi", visitors: 118 },
    { country: "US", city: "San Francisco", visitors: 84 },
    { country: "GB", city: "London", visitors: 76 },
    { country: "DE", city: "Berlin", visitors: 41 },
    { country: "SG", city: "Singapore", visitors: 38 },
    { country: "AE", city: "Dubai", visitors: 29 },
    { country: "CA", city: "Toronto", visitors: 22 },
  ],
};
