// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-themes/EditorialWarm.tsx": () => import("../components/mockups/landing-themes/EditorialWarm.tsx"),
  "./components/mockups/landing-themes/LinearMinimal.tsx": () => import("../components/mockups/landing-themes/LinearMinimal.tsx"),
  "./components/mockups/landing-themes/Scheme1.tsx": () => import("../components/mockups/landing-themes/Scheme1.tsx"),
  "./components/mockups/landing-themes/Scheme2.tsx": () => import("../components/mockups/landing-themes/Scheme2.tsx"),
  "./components/mockups/landing-themes/Scheme3.tsx": () => import("../components/mockups/landing-themes/Scheme3.tsx"),
  "./components/mockups/landing-themes/StripePremium.tsx": () => import("../components/mockups/landing-themes/StripePremium.tsx"),
  "./components/mockups/luxor-invoices/AllInvoices.tsx": () => import("../components/mockups/luxor-invoices/AllInvoices.tsx"),
  "./components/mockups/luxor-invoices/Aurora.tsx": () => import("../components/mockups/luxor-invoices/Aurora.tsx"),
  "./components/mockups/luxor-invoices/BoldBranded.tsx": () => import("../components/mockups/luxor-invoices/BoldBranded.tsx"),
  "./components/mockups/luxor-invoices/ClassicProfessional.tsx": () => import("../components/mockups/luxor-invoices/ClassicProfessional.tsx"),
  "./components/mockups/luxor-invoices/Editorial.tsx": () => import("../components/mockups/luxor-invoices/Editorial.tsx"),
  "./components/mockups/luxor-invoices/MidnightRoyal.tsx": () => import("../components/mockups/luxor-invoices/MidnightRoyal.tsx"),
  "./components/mockups/luxor-invoices/Minimal.tsx": () => import("../components/mockups/luxor-invoices/Minimal.tsx"),
  "./components/mockups/luxor-invoices/Obsidian.tsx": () => import("../components/mockups/luxor-invoices/Obsidian.tsx")
};
