// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-themes/EditorialWarm.tsx": () => import("../components/mockups/landing-themes/EditorialWarm.tsx"),
  "./components/mockups/landing-themes/LinearMinimal.tsx": () => import("../components/mockups/landing-themes/LinearMinimal.tsx"),
  "./components/mockups/landing-themes/StripePremium.tsx": () => import("../components/mockups/landing-themes/StripePremium.tsx")
};
